import Head from "next/head";
import Container from "@/components/Container";
import SwiperComponent from "@/components/Swiper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h2>Main</h2>
          <SwiperComponent />
        </Container>
      </main>
    </>
  );
}
